version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: deepak-omniroute_server_1
      APP_PORT: 20128

  server:
    image: diegosouzapw/omniroute:next@sha256:8d38150fa55b6f499a408a469e7f715a1c9f90be4b97c7fb2b023796ac29633e
    user: "0:0"
    restart: on-failure
    stop_grace_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
