version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: deepak-omniroute_server_1
      APP_PORT: 20128

  server:
    image: diegosouzapw/omniroute:3.8.50@sha256:085c57adf499a8aaa9f35ccde95c0df9c11bd9ecd18d6c9edbf3b68b8079ba9d
    restart: on-failure
    stop_grace_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
