version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: deepak-brave_server_1
      APP_PORT: 3000

  server:
    image: lscr.io/linuxserver/brave:latest
    restart: on-failure
    stop_grace_period: 1m
    shm_size: "1gb"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
